

map.path = Asset/rsrc/maps/lvl1.txt

# Vitesse
ice.speed = 20.0
ice.friction = 0.9992

# Bonus temporaire
fish.boost.duration = 8000
gold.freeze.duration = 5000
gold.doubleScore.duration = 5000

# Score
score.crush = 100