/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int KEY = 6;
  /** RegularExpression Id. */
  int CONDITION = 7;
  /** RegularExpression Id. */
  int ACTION = 8;
  /** RegularExpression Id. */
  int SPECIAL_KEY = 9;
  /** RegularExpression Id. */
  int DIRVAR = 10;
  /** RegularExpression Id. */
  int CATVAR = 11;
  /** RegularExpression Id. */
  int ENTVAR = 12;
  /** RegularExpression Id. */
  int DOLLAR = 13;
  /** RegularExpression Id. */
  int DIRECTION = 14;
  /** RegularExpression Id. */
  int OPPOSITE = 15;
  /** RegularExpression Id. */
  int CATEGORY = 16;
  /** RegularExpression Id. */
  int MOUSE = 17;
  /** RegularExpression Id. */
  int UNDERSCORE = 18;
  /** RegularExpression Id. */
  int CAPITAL = 19;
  /** RegularExpression Id. */
  int LOWERCASE = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int UNARY = 23;
  /** RegularExpression Id. */
  int CONJUNCTION = 24;
  /** RegularExpression Id. */
  int DISJUNCTION = 25;
  /** RegularExpression Id. */
  int SEQUENCE = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Key\"",
    "<CONDITION>",
    "<ACTION>",
    "<SPECIAL_KEY>",
    "\"d\"",
    "\"c\"",
    "\"e\"",
    "\"$\"",
    "<DIRECTION>",
    "\"opposite\"",
    "<CATEGORY>",
    "<MOUSE>",
    "\"_\"",
    "<CAPITAL>",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "\"!\"",
    "\"&\"",
    "\"/\"",
    "\";\"",
    "<ID>",
    "<INTEGER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\":\"",
    "\"|\"",
    "\"?\"",
    "\"%\"",
    "\",\"",
    "\"\\u00b0\"",
    "\".\"",
  };

}
